=== fengchangsheng/mybatis-analysis/src/test/java/com/ibatis/dao/engine/builder/xml/dao-2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2012 The MyBatis Team

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT daoConfig (properties? , context+)>

<!ELEMENT context (transactionManager, dao*)+>
<!ATTLIST context
id CDATA #IMPLIED
>

<!ELEMENT properties EMPTY>
<!ATTLIST properties
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT transactionManager (property*)>
<!ATTLIST transactionManager
type CDATA #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT dao EMPTY>
<!ATTLIST dao
interface CDATA #REQUIRED
implementation CDATA #REQUIRED
>

=== fengchangsheng/mybatis-analysis/src/test/java/com/ibatis/jpetstore/persistence/dao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2012 The MyBatis Team

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE daoConfig
    PUBLIC "-//ibatis.apache.org//DTD DAO Configuration 2.0//EN"
    "http://ibatis.apache.org/dtd/dao-2.dtd">

<daoConfig>

  <context>

    <transactionManager type="SQLMAP">
      <property name="SqlMapConfigResource"
                value="com/ibatis/jpetstore/persistence/sqlmapdao/sql/sql-map-config.xml"/>
    </transactionManager>

    <dao interface="com.ibatis.jpetstore.persistence.iface.ItemDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.ItemSqlMapDao"/>

    <dao interface="com.ibatis.jpetstore.persistence.iface.SequenceDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.SequenceSqlMapDao"/>

    <dao interface="com.ibatis.jpetstore.persistence.iface.AccountDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.AccountSqlMapDao"/>

    <dao interface="com.ibatis.jpetstore.persistence.iface.CategoryDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.CategorySqlMapDao"/>

    <dao interface="com.ibatis.jpetstore.persistence.iface.ProductDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.ProductSqlMapDao"/>

    <dao interface="com.ibatis.jpetstore.persistence.iface.OrderDao"
         implementation="com.ibatis.jpetstore.persistence.sqlmapdao.OrderSqlMapDao"/>

  </context>

</daoConfig>
